#!/bin/bash

if [ $(pgrep -cx panel) -gt 1 ] ; then
   printf "%s\n" "The panel is already running." >&2
   exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

source ~/.config/bspwm/panel_profile

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

bspc config top_padding $PANEL_HEIGHT
bspc control --subscribe > "$PANEL_FIFO" &
xtitle -s -f 'T%.70s' > "$PANEL_FIFO" &
battery -n 1 -s -f 'B (%d%%%%) ' > "$PANEL_FIFO" &
essid -s -w wlp2s0 -f 'E %s ' > "$PANEL_FIFO" &
clock -s -i 1 -f 'C %F %H:%M ' > "$PANEL_FIFO" &

cat "$PANEL_FIFO" | ~/.config/bspwm/panel_bar | lemonbar -g x$PANEL_HEIGHT -f "$PANEL_FONT_FAMILY" -F "$COLOR_FOREGROUND" -B "$COLOR_BACKGROUND" &

wait
