#! /bin/bash

source ~/.config/bspwm/panel_profile

num_mon=$(bspc query -M | wc -l)

while read -r line; do
    case $line in
         T*)
             #xtitle output
             title="%{F$COLOR_TITLE} ${line#?} %{F-}"
             ;;
         B*)
             #battery output
             battery="%{F$COLOR_FOREGROUND}${line#?}%{F-}"
             ;;
         E*)
             #essid output
             essid="%{F$COLOR_FOREGROUND}${line#?}%{F-}"
             ;;
         C*)
             #clock output
             clock="%{F$COLOR_FOREGROUND}${line#?}%{F-}"
             ;;
         W*)
             #bspwm internal state
             wm_infos=""
             IFS=':'
             set -- ${line#?}
             while [ $# -gt 0 ]; do
                item=$1
                name=${item#?}
                case $item in
                     M*)
                         #active monitor
                         if [ $num_mon -gt 1 ] ; then
                            wm_infos="$wm_infos %{F$COLOR_ACTIVE} ${name} %{F-}"
                         fi
                         ;;
                     m*)
                         #inactive monitor
                         if [ $num_mon -gt 1 ] ; then
                             wm_infos="$wm_infos %{F$COLOR_FREE} ${name} %{F-}"
                         fi
                         ;;
                     O*)
                         #focused occupied desktop
                         wm_infos="${wm_infos}%{F$COLOR_ACTIVE} ${name} %{F-}"
                         ;;
                     F*)
                         #focused free desktop
                         wm_infos="${wm_infos}%{F$COLOR_ACTIVE} ${name} %{F-}"
                         ;;
                     U*)
                         #focused urgent desktop
                         wm_infos="${wm_infos}%{F$COLOR_URGENT} ${name} %{F-}"
                         ;;
                     o*)
                         #occupied desktop
                         wm_infos="${wm_infos}%{F$COLOR_OCCUPIED} ${name} %{F-}"
                         ;;
                     f*)
                         #free desktop
                         wm_infos="${wm_infos}%{F$COLOR_FREE} ${name} %{F-}"
                         ;;
                     u*)
                         #urgent desktop
                         wm_infos="${wm_infos}%{F$COLOR_URGENT} ${name} %{F-}"
                         ;;
                esac
                shift
             done
             ;;
    esac
    printf "%s\n" "%{l}${wm_infos}%{c}${title}%{r}${essid}${battery}${clock}"

done
